### ISSUE TITLE
Cloning error

### ISSUE THREAD

**Issue by sheppyrsa** [CrowdStrike/logscale-community-content#63]
Hey All,

I get an error cloning this repo as follows:

error: invalid path 'Log-Sources/LogScale-Internal/src/alerts/LogScaleLogCollectorErrors>5in30minutewindow.yaml'
error: invalid path 'Log-Sources/Microsoft/AzureAD:EntraID/build.sh'
error: invalid path 'Log-Sources/Microsoft/AzureAD:EntraID/microsoft--azuread--0.1.0.zip'
error: invalid path 'Log-Sources/Microsoft/AzureAD:EntraID/src/README.md'
error: invalid path 'Log-Sources/Microsoft/AzureAD:EntraID/src/dashboards/ApplicationManagement.yaml'
error: invalid path 'Log-Sources/Microsoft/AzureAD:EntraID/src/dashboards/DirectoryManagement.yaml'
error: invalid path 'Log-Sources/Microsoft/AzureAD:EntraID/src/dashboards/FailedSignIns.yaml'

I'm not sure what causes this error but I think it is related to > being an invalid character in the file path. In which case the first file path would need to have its name changed. But I might be wrong, are others able to download this successfully?

thanks,
Andrew

**Comment by nlabadie-crwd** [comment]
No issues here, I just cloned it to check. Still having a problem cloning it?

**Comment by brysonlt** [comment]
It seems to be an issue cloning using Git for Windows. My workaround was cloning into a Linux distro on WSL2.
